# Generated by Django 3.2.4 on 2021-06-18 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('tfno', models.CharField(max_length=10)),
            ],
        ),
    ]
